# Generated by Django 4.2.3 on 2023-07-21 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resposta_resposta_alter_luiza_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='luiza',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c5130f0-c4c2-40e8-acf1-ad242a3ea739'), primary_key=True, serialize=False),
        ),
    ]
