# Generated by Django 4.2.3 on 2023-07-26 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pergunta_alter_luiza_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasFuturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='luiza',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97555340-4c08-47f4-bbbf-13a6dee692c6'), primary_key=True, serialize=False),
        ),
    ]
