# Generated by Django 4.2.3 on 2023-07-31 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_luiza_id_alter_pergunta_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luiza',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eaebbc2f-50b4-4792-bce5-7a00df7c2c6e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
