# Generated by Django 4.2.3 on 2023-08-01 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_luiza_id_alter_resposta_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palavras',
            fields=[
                ('id_palavras', models.UUIDField(auto_created=True, default=uuid.UUID('25f2c330-4726-457a-a108-4ab0fc589174'), editable=False, primary_key=True, serialize=False)),
                ('json_palavras', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(auto_created=True, default=uuid.UUID('de749dd4-3e03-41be-a00b-ef67cad276b8'), editable=False, primary_key=True, serialize=False)),
                ('senha', models.TextField(default=uuid.UUID('c4ba0a75-e93c-4e20-a0c1-c23c3175862b'), max_length=100)),
                ('nome', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Luiza',
        ),
        migrations.DeleteModel(
            name='PerguntasFuturas',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='id',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('06ec2ca1-d2a9-47b9-914a-a8fc0ca01b8c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e38b2b60-821d-4c16-9983-d924041d7d42'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(default='Insira uma pergunta', max_length=2000),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.TextField(default='insira uma resposta', max_length=2000),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='id_usuario',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Pergunta_Usuario', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='id_usuario',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Resposta_Usuario', to='api.usuario'),
        ),
    ]
