# Generated by Django 4.2.3 on 2023-08-01 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_palavras_usuario_delete_luiza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('59bd7c0d-40d8-4d28-9e7e-d663dd94d06c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.UUID('ac8c0475-74f7-4e00-84bf-ff1b7ca4695c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('c4e5407f-7d7d-4f4b-a03e-365fc808d391'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('bbffccc8-3cd7-4b73-b33c-da3881060377'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('b09b4e6d-d911-42bf-9c37-8491dce53b45'), max_length=100),
        ),
    ]
