# Generated by Django 4.2.3 on 2023-08-01 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('55fbd2f6-2104-4290-a027-225e82aeff97'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.UUID('51b75fd1-a637-42ed-8fcd-c19e966074dc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Pergunta_Usuario', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('a7c06197-8306-447a-9bbb-0a18e4c6c8fe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Resposta_Usuario', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('9d997022-eada-41cd-b12d-eaf45ed2d8fa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('3da7552c-8c29-4deb-bf9d-02d61c6cc959'), max_length=100),
        ),
    ]
