# Generated by Django 4.2.4 on 2023-08-01 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('7d419297-b384-4c3c-a18e-fef91012a1af'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.UUID('82c1b430-561d-404e-8f06-ac66e4b14e3b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('709a1efa-156c-44ea-b1bf-df21c0dd7ac4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('45924691-ded5-4a52-9d5b-de86c75fd05a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('94594c70-5410-4304-a2c0-4b0ef77d0271'), max_length=100),
        ),
    ]
