# Generated by Django 4.2.4 on 2023-08-04 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_treinamento1_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('0fcf1bf2-207a-4576-9ba6-e1ffbe824267'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.UUID('55b6849d-1793-4786-93f5-a63f0300f60b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('cb9f362c-54a6-48f3-99fa-8269ee52a282'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('58808b15-f9ac-4f1c-bc31-49dacaaa75e3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('07e439cf-f37d-4bce-b0b9-be4614b8ea60'), max_length=100),
        ),
    ]
