# Generated by Django 4.2.4 on 2023-08-04 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_pergunta_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('9f332ec5-9302-41f3-b48c-1d1a72020590'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('3675ccac-6864-4ba6-8ddf-5c2ce4d1d992'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('ebafb5cf-6de3-47a4-bd04-3e3ebe13473b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('a3fc9562-f84a-4ed9-86dd-518a0250e25f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('388eb6d0-1338-4653-a582-93453c253f82'), max_length=100),
        ),
    ]
