# Generated by Django 4.2.4 on 2023-08-04 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('d4a86945-a912-45c2-9219-d1ad41ad6a2e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.UUID('aff5a394-63d0-47ab-b880-50040bc1c556'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('c90be721-5d8a-4eae-afa7-9c743ad5af92'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('8c880e02-ba2e-4692-b736-fb5c57613199'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('89a7da8d-c0d4-452a-974f-51abd1567011'), max_length=100),
        ),
    ]
