# Generated by Django 4.2.4 on 2023-08-04 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('c4916926-5ab8-4b6c-ac59-2925a76be2d0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.UUID('17be6d22-e2ec-4e24-956b-78c8aceac926'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('086bb308-6acd-4710-8a0d-fcd880229328'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('c2dcfda9-c27c-4111-a68d-ef0bfcb07f24'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('124c7f32-cbb9-49ed-a23c-2cf21440c0dc'), max_length=100),
        ),
    ]
