# Generated by Django 4.2.4 on 2023-08-04 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('b386d58c-1b15-4eb8-9803-221061fefd10'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('c93caba8-bade-415c-a430-fca8db7cd8be'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('5afc363b-a8af-4e29-bf63-0fffe6194285'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('4280855a-c0eb-407b-90e0-423e9572684f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('773818ea-d9ca-4920-a87d-5cf9ede9085d'), max_length=100),
        ),
    ]
