# Generated by Django 4.2.4 on 2023-08-04 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_palavras_id_palavras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavras',
            name='id_palavras',
            field=models.UUIDField(default=uuid.UUID('8331d710-f842-487d-a9cd-f496a72a8072'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_resposta',
            field=models.UUIDField(default=uuid.UUID('edbd5b88-416f-4097-88fb-acabbfe9558f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('a366d802-6ea3-4904-a48f-a4f7f3a0a55f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=uuid.UUID('2f831b9f-4f7b-4432-a9d7-f4aeebb2f0d1'), max_length=100),
        ),
    ]
