# Generated by Django 4.2.4 on 2023-09-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_treinamentos_imagem_imagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagens',
            old_name='id_imagem_curso',
            new_name='id_treinamento',
        ),
    ]
