# Generated by Django 4.2.4 on 2023-09-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_id_imagem_curso_imagens_id_treinamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.FileField(upload_to='media'),
        ),
    ]
