# Generated by Django 4.2.4 on 2023-09-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_imagens_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamentos',
            name='imagem',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
