# Generated by Django 4.2.4 on 2023-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_treinamentos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='descricao',
            field=models.CharField(max_length=350),
        ),
    ]
