# Generated by Django 4.2.4 on 2023-10-17 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_treinamentos_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id_questionario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questao_1', models.CharField(choices=[('1', 'Facilitar despesas pessoais.'), ('2', 'Simplificar despesas comerciais.'), ('3', 'Acumular pontos de recompensa para o funcionário.'), ('4', 'Nenhuma das Anteriores.')], max_length=1)),
                ('questao_2', models.CharField(choices=[('1', 'Verdadeiro'), ('2', 'Falso'), ('3', 'Nenhuma das Anteriores.')], max_length=1)),
                ('questao_3', models.CharField(choices=[('1', 'Conta Corrente'), ('2', 'Poupança'), ('3', 'Conta Salário'), ('4', 'Conta de Depósitos')], max_length=1)),
                ('questao_4', models.CharField(choices=[('1', 'Não é importante; você pode usá-lo imediatamente.'), ('2', 'Para garantir que o cartão seja ativado e funcione corretamente.'), ('3', 'Para acumular recompensas antes de desbloquear.')], max_length=1)),
                ('questao_5', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
