# Generated by Django 4.2.4 on 2023-10-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_questionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='questao_5',
            field=models.CharField(choices=[('1', 'Não é importante; você pode usá-lo imediatamente.'), ('2', 'Para garantir que o cartão seja ativado e funcione corretamente.'), ('3', 'Para acumular recompensas antes de desbloquear.')], max_length=1),
        ),
    ]
