# Generated by Django 4.2.7 on 2023-11-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_questionario_id_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Palavras',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
