# Generated by Django 4.2.7 on 2023-11-14 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_delete_palavras_delete_pergunta_delete_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('documento', models.FileField(unique=True, upload_to='Documents')),
            ],
        ),
    ]
