# Generated by Django 4.2.6 on 2023-11-14 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_mensagem', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mensagem', models.CharField(max_length=1000)),
            ],
        ),
    ]
